src/objects/CallIntelligenceSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Stores the configuration settings for Call Intelligence</description>
    <fields>
        <fullName>RecordsToShow__c</fullName>
        <label>Maximum Records To Show</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_for_Records__c</fullName>
        <inlineHelpText>Show the record which are created in last n hours. n - Hours entered</inlineHelpText>
        <label>Time for Records</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Call Intelligence Settings</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Caller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to the caller for which this case was created</description>
        <label>Caller</label>
        <referenceTo>CGTC_CallingNumber__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CGTC_CallingNumber__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caller Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Calling Numbers</relationshipLabel>
        <relationshipName>Callers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Of_Interest__c</fullName>
        <description>Stores the product name given for each page</description>
        <label>Product Of Interest</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Calling Number</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{0}</displayFormat>
        <label>Blocked #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calling Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stores if the contact is blocked or not</description>
        <label>Is Blocked</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CallMeBackInboundNotificationController.cls
/**
 * Created by Manjit Singh on 10 October 2017.
 */

public with sharing class CallMeBackInboundNotificationController {
    public List<Case> lstCasesInQueue { get; set; }

    public void fetchCases() {
        Integer casesToShow = (Integer) CallIntelligenceSettings__c.getInstance().RecordsToShow__c;
        Integer timeToShow = (Integer) CallIntelligenceSettings__c.getInstance().Time_for_Records__c * (-1);

        lstCasesInQueue = [
                SELECT CaseNumber,Id,Caller__r.Product_Of_Interest__c, Caller__r.Caller_Name__c, Contact.Phone
                FROM Case
                where OwnerId = :UserInfo.getUserId()
                AND IsClosed = false
                AND Contact.Is_Blocked__c = false
                AND CreatedDate >= :Date.today().addDays(timeToShow)
                LIMIT :casesToShow
        ];

    }

}