src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Caller_Location__c</fullName>
        <label>Caller Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caller__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Links to the caller for which this case was created</description>
        <label>Caller</label>
        <referenceTo>CGTC_CallingNumber__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/CGTC_CallingNumber__c.object
<CustomObject>
    <fields>
        <fullName>Caller_Location__c</fullName>
        <description>Save the location from which the caller called</description>
        <label>Caller Location</label>
        <scale>8</scale>
        <type>Location</type>
    </fields>
    <fields>
        <fullName>Caller_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Caller Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Calling Numbers</relationshipLabel>
        <relationshipName>Callers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page_URL__c</fullName>
        <description>Stores the page URL from which the user navigated.</description>
        <label>Page URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Product_Of_Interest__c</fullName>
        <description>Stores the product name given for each page</description>
        <label>Product Of Interest</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Calling Number</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{0}</displayFormat>
        <label>Blocked #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Calling Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stores if the contact is blocked or not</description>
        <label>Is Blocked</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CallMeBackInboundNotificationUtility.cls
/**
 * Created by Manjit Singh on 10 October 2017.
 */

public with sharing class CallMeBackInboundNotificationUtility {

    /*
    * This method checks if the number is valid
    * @param String Phone Number
    * @return Returns if the number is valid or not.
     */
    public Boolean checkIfNumberIsValid(String strPhoneNumber) {
        Pattern objNumericPattern = Pattern.compile('\\+[0-9]{1,2}[0-9]{10}'); // Checks for 9 digit nuber with country code
        if (String.isNotBlank(strPhoneNumber)) {
            Matcher objMatcher = objNumericPattern.matcher(strPhoneNumber);
            if (objMatcher.matches()) {
                return true;
            } else {
                return false;
            }
        } else {
            return false ;
        }
    }

    /*
    * This method checks if the number is blocked or not
    * @param String Phone Number
    * @return Returns if the number is blocked or not.
    */
    public Boolean checkIfNumberIsBlocked(String strPhoneNumber) {
        return [SELECT count() from Contact where Is_Blocked__c = true AND Phone = :strPhoneNumber] != 0;
    }

    /*
    * This creates a case
    * @param idContactId
    * @param idCallerId
    */
    public void createCase(Id idContactId, Id idCallerId, String strProduct, String strLocation) {
        insert new Case(ContactId = idContactId, Caller__c = idCallerId, Subject = strProduct, Caller_Location__c = strLocation);

    }

    /*
    * This creates calling number record
    * @return Created Calling record
    */
    public CGTC_CallingNumber__c createCallingRecord(String strCallerName, String strPhoneNumber, String strPageUrl, Decimal decLatitude, Decimal decLongitude, String strProduct) {
        CGTC_CallingNumber__c objCall = new CGTC_CallingNumber__c();
        objCall.Caller_Location__Latitude__s = decLatitude;
        objCall.Caller_Location__Longitude__s = decLongitude;
        objCall.Caller_Name__c = fetchCallingContact(strPhoneNumber, strCallerName);
        objCall.Page_URL__c = strPageUrl;
        objCall.Product_Of_Interest__c = strProduct;
        insert objCall;
        return objCall;
    }

    /*
    * This creates calling number record
    * @return Created Contact Id
    */
    public Id fetchCallingContact(String strPhoneNumber, String strName) {
        List<Contact> lstContacts = [SELECT Id, Name from Contact where Phone = :strPhoneNumber LIMIT 1];
        if (lstContacts.size() > 0) {
            return lstContacts[0].Id;
        } else {
            Contact objContact = new Contact(LastName = strName, Phone = strPhoneNumber);
            insert objContact;
            return objContact.Id;
        }
    }


}